name: flutter_base
description: A base Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  asuka: ^2.0.0
  auto_route: ^5.0.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  flutter_config: ^2.0.0
  flutter_loggy: ^2.0.1
  flutter_svg: ^1.1.5
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  dio: ^4.0.6
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^6.0.0
  loggy: ^2.0.1
  meta: ^1.7.0
  package_info_plus: ^1.4.3
  rxdart: ^0.27.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  bloc_test: ^9.0.3
  mocktail: ^0.3.0
  integration_test:
    sdk: flutter
  freezed: ^2.1.0
  json_serializable: ^6.4.0
  auto_route_generator: ^5.0.0
  hive_generator: ^1.1.3
  flutter_gen_runner: ^5.0.1
  intl_utils: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/generated/

  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false

  assets:
    enabled: true
    package_parameter_enabled: false
    style: dot-delimiter

  fonts:
    enabled: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml

flutter_intl:
  enabled: true
  main_locale: 'zh_Hant'
  arb_dir: assets/l10n
